/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package election_management_system;

import java.awt.BorderLayout;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author DELL
 */
public class VoterForm extends javax.swing.JFrame {
    private JLabel countdownLabel;
    private TimerUtil timerUtil;
    private String sendToServer(String request) {
    try (Socket socket = new Socket("localhost", 12346);
         PrintWriter out = new PrintWriter(socket.getOutputStream(), true);
         BufferedReader in = new BufferedReader(new InputStreamReader(socket.getInputStream()))) {

        out.println(request);
        return in.readLine();
    } catch (IOException e) {
        e.printStackTrace();
        return "ERROR:" + e.getMessage();
    }
}
    
    
public VoterForm() throws ParseException {
    initComponents();

    Timer.setText("⏳ Checking election status...");
    Timer.setHorizontalAlignment(SwingConstants.CENTER);
    Timer.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
    Timer.setForeground(new java.awt.Color(255, 255, 255)); // white text


    String status = sendToServer("getElectionStatus;");
    if (status.equals("Started")) {
        String stopTimeStr = sendToServer("selectElectionStopTime;");
        if (!stopTimeStr.equals("NONE") && !stopTimeStr.startsWith("ERROR")) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            Date stopTime = sdf.parse(stopTimeStr);
            timerUtil = new TimerUtil(Timer); // Use GUI Timer label
            timerUtil.startCountdown(stopTime);
        } else {
            Timer.setText("⏳ Waiting for stop time...");
        }
    } else {
        Timer.setText("⏳ Voting has not started yet.");
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        C_N = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btn3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        R_T = new javax.swing.JTable();
        btn4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Cnic = new javax.swing.JTextField();
        check1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        CAST_T = new javax.swing.JTable();
        btn1 = new javax.swing.JButton();
        Timer = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();
        Cnic2 = new javax.swing.JTextField();
        check = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(0, 102, 51));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setOpaque(true);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        C_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_NActionPerformed(evt);
            }
        });
        jPanel4.add(C_N, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 350, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Enter Your Constitution:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        btn3.setBackground(new java.awt.Color(0, 102, 51));
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("Check Results By Constitution");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel4.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 200, 40));

        R_T.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(R_T);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 570, 380));

        btn4.setBackground(new java.awt.Color(0, 102, 51));
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("Check Result By Parties");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel4.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 170, 40));

        jButton8.setBackground(new java.awt.Color(0, 102, 51));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("<< Log Out");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 100, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/election_management_system/R.jpeg"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 550));

        jTabbedPane1.addTab("check result", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Enter Your CNIC:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        Cnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CnicActionPerformed(evt);
            }
        });
        jPanel5.add(Cnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 400, 30));

        check1.setBackground(new java.awt.Color(0, 102, 51));
        check1.setForeground(new java.awt.Color(255, 255, 255));
        check1.setText("Verify");
        check1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check1ActionPerformed(evt);
            }
        });
        jPanel5.add(check1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 100, 30));

        CAST_T.setAutoCreateRowSorter(true);
        CAST_T.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        CAST_T.setShowGrid(false);
        jScrollPane2.setViewportView(CAST_T);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 90, 560, 250));

        btn1.setBackground(new java.awt.Color(0, 102, 51));
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("Cast Vote");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel5.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 110, 40));

        Timer.setText("jLabel1");
        jPanel5.add(Timer, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 240, 60));

        jLabel5.setBackground(new java.awt.Color(255, 51, 51));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/election_management_system/R.jpeg"))); // NOI18N
        jLabel5.setText("jLabel2");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 550));

        jButton7.setBackground(new java.awt.Color(0, 102, 51));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("<< Log Out");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 100, 40));

        jTabbedPane1.addTab("cast vote", jPanel5);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Enter Your CNIC:");
        jLayeredPane1.add(jLabel11);
        jLabel11.setBounds(30, 160, 150, 40);

        Cnic2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cnic2ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Cnic2);
        Cnic2.setBounds(140, 200, 280, 30);

        check.setBackground(new java.awt.Color(0, 102, 51));
        check.setForeground(new java.awt.Color(255, 255, 255));
        check.setText("Verify");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });
        jLayeredPane1.add(check);
        check.setBounds(220, 250, 110, 40);

        jPanel2.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 550, 360));

        jButton9.setBackground(new java.awt.Color(0, 102, 51));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("<< Log Out");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 110, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/election_management_system/R.jpeg"))); // NOI18N
        jLabel3.setText("jLabel2");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 910, 580));

        jTabbedPane1.addTab("search", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void C_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C_NActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        Results.showSeatResults(C_N, R_T,btn3 );
    }//GEN-LAST:event_btn3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
            new LoginForm().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
            new LoginForm().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void Cnic2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cnic2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cnic2ActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // TODO add your handling code here:
        Search.confirmVoterRegistration(Cnic2, CAST_T, jTabbedPane1);
    }//GEN-LAST:event_checkActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
            new LoginForm().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
            String voterCnic = Cnic.getText().trim();      // or from session
            ElectionTimeRegistrar.handleVote(CAST_T, voterCnic, btn1);
    }//GEN-LAST:event_btn1ActionPerformed

    private void CnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CnicActionPerformed

    private void check1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check1ActionPerformed
        // TODO add your handling code here:
        Search.confirmVoterRegistration(Cnic, CAST_T, jTabbedPane1);
    }//GEN-LAST:event_check1ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        Results.showPartyResults(C_N, R_T,btn4 );
    }//GEN-LAST:event_btn4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VoterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VoterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VoterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VoterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VoterForm().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(VoterForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CAST_T;
    private javax.swing.JTextField C_N;
    private javax.swing.JTextField Cnic;
    private javax.swing.JTextField Cnic2;
    private javax.swing.JTable R_T;
    private javax.swing.JLabel Timer;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton check;
    private javax.swing.JButton check1;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
